[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    '@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/',
    '@openzeppelin/contracts=lib/openzeppelin-contracts/contracts',
    '@chainlink/contracts-ccip/=lib/ccip-contracts/contracts-ccip/',
    '@AA/contracts=lib/account-abstraction/contracts',
    '@zkAA/contracts=lib/foundry-era-contracts/src/system-contracts/contracts'
]
is-system = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
